### ISSUE TITLE
is there a way to keep script security enabled?

### ISSUE THREAD

**Issue by alexeygrigorovaurea** [samrocketman/jervis#119]
Hi Sam , in Importer job dsl job there is additional classpath , which is not available when script security is turned on. Is there a way how it can be white listed to keep script security on?
Thanks

**Comment by alexeygrigorovaurea** [comment]
yes

**Comment by samrocketman** [comment]
At the moment, no; it's not something I'm investigating at this time because it is assumed _only admins_ have the ability to create jobs.  And, in reality, even admins don't need that ability.  Job creation through metadata in a repository is how Jobs get created so it is not possible to exploit through normal means in which it was invented.

This could change down the line but it's not worth investing time in for me at the moment given the scope of the perceived risk.

**Comment by alexeygrigorovaurea** [comment]
Got it, thanks
I have Jenkins instances where users can run their jobs, So sniping new master for jervis only I guess should be safest option.

**Comment by samrocketman** [comment]
Yeah, I would agree.  In its current form, it's not designed to be patchwork added to another Jenkins instance.  Mainly because there's specific plugin requirements to take advantage of the features.

The access control is still really lacking as well.  That's going to be improved.  For immutable packages of all of the plugins required by Jervis you can download a custom version of Jenkins provided by https://github.com/samrocketman/jenkins-bootstrap-jervis/releases

Those packages are built by https://github.com/samrocketman/jenkins-bootstrap-shared/blob/21f76bb94f89dbbd56e8697482c861266c2b456a/RELEASE.md

Versions of plugins defined in https://github.com/samrocketman/jenkins-bootstrap-jervis/blob/master/dependencies.gradle

**Comment by alexeygrigorovaurea** [comment]
already on it 👍  Great repos, great scripts, this one definitely my favorite https://github.com/samrocketman/jenkins-bootstrap-shared/blob/master/scripts/jenkins-call-url 🥇

**Comment by samrocketman** [comment]
Thanks :) you might also like https://github.com/samrocketman/home/tree/master/bin#jenkins-productivity-scripts .  My favorite is `jenkins_wait_job.sh` which uses `jenkins-call-url`.
